CREATE DATABASE store;
USE store;
CREATE TABLE Registration ( Name TEXT NOT NULL , DOB VARCHAR(20) NOT NULL , Email VARCHAR(50) NOT NULL , Mobile_Number BIGINT NOT NULL , Gender TEXT NOT NULL , Address VARCHAR(100) NOT NULL , Password VARCHAR(20) NOT NULL , PRIMARY KEY (Email(20)), UNIQUE (Mobile_Number));
CREATE TABLE Login ( SNO INT AUTO_INCREMENT, UID VARCHAR(50) NOT NULL , Date_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (SNO))AUTO_INCREMENT=1;
CREATE TABLE ShopDetails (ID INT, Shop_Name VARCHAR(30) NOT NULL , Owner_Name VARCHAR(20) NOT NULL , Phone_Number BIGINT NOT NULL , Email VARCHAR(50) NOT NULL , Shop_Address VARCHAR(100) NOT NULL );
INSERT INTO ShopDetails VALUES("1", "KOSMAA ELECTRONICS", "Bharat KOSMAA", "9958246675", "kosmaa@gmail.com", "SHOP NO. 1, PALIKA BAZAAR, CONNAUGHT PALACE, DELHI - 110001");
CREATE TABLE ProductRecords ( SU VARCHAR(30), Product_Name VARCHAR(30) NOT NULL , Cost FLOAT NOT NULL, PRIMARY KEY(SU) );
CREATE TABLE CustomerRecords ( Customer_Name VARCHAR(30) NOT NULL , Customer_Phno BIGINT NOT NULL , Customer_Email VARCHAR(50) DEFAULT "N/A", Customer_Address VARCHAR(100) DEFAULT "N/A", Seller VARCHAR(20) NOT NULL , Total_Price FLOAT NOT NULL, Purchase_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, Bill_No INT NOT NULL UNIQUE AUTO_INCREMENT, PRIMARY KEY(Bill_no))AUTO_INCREMENT=100;
CREATE TABLE Bill (Bill_No INT NOT NULL, SU VARCHAR(30),Product_Name VARCHAR(30),  QTY INT, Cost FLOAT, FOREIGN KEY (Bill_No) REFERENCES CustomerRecords (Bill_no)); 